# Generated by Django 6.0 on 2025-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blackspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeHeatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('crime_description', models.CharField(blank=True, max_length=255, null=True)),
                ('crime_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_age', models.IntegerField(blank=True, null=True)),
                ('weapon_used', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
